# Generated by Django 3.1.1 on 2020-10-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Produto',
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['id'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
